name: 'hide test'

on: [ workflow_dispatch ]

jobs:
  hide:
    steps:
      - using: 'node16'
      - main: 'hide_archived_repositories.js'

# name: 'hide test'

# on: [ workflow_dispatch ]

# runs:
#   using: 'node16'
#   main: 'hide_archived_repositories.js'
